### ISSUE TITLE
Audio playing test sound, but no other audio

### ISSUE THREAD

**Issue by luw** [sonocotta/tas5805m-for-raspbian-paspberry-pi-zero#1]
I am able to get the instructed beep to come out the speaker using `speaker-test -t sine -f 500 -c 2`  
However that's it.

Audio program I use and am familiar with is called cmus.  It lists this at at launch 
`dietpi@DietPi:~$ cmus
cmus: Error: an error occured while initializing MPRIS: No medium found. MPRIS will be disabled.
`

Then when I try to play a song, the RPi locks up, except only the following from the serial port 
[audio_causing_lockup.txt](https://github.com/sonocotta/tas5805m-for-raspbian-paspberry-pi-zero/files/15366701/audio_causing_lockup.txt)

also on boot this is in dmesg...
`[    7.073838] tas5805m 1-002d: Direct firmware load for tas5805m_dsp_default.bin failed with error -2
[    7.073872] tas5805m 1-002d: firmware not found, using minimal config
`
full boot dmesg here 
[dmesg.txt](https://github.com/sonocotta/tas5805m-for-raspbian-paspberry-pi-zero/files/15366677/dmesg.txt)

Any idea how I can get this to play a song?

**Comment by anabolyc** [comment]
Can you please check how may devices alsa able to find
```
aplay -l
```

Can you please also check if you can play using something simple like `mpg123` app. Just asking since I'm not familiar with the `cmus` and I'm not sure while interface it is using

The question regarding power source from the other issue will be valid here also

**Comment by luw** [comment]
Sure thank you for your time.  I will try mpg123.  In the meantime...

`dietpi@DietPi:~$ aplay -l
aplay: device_list:274: no soundcards found...
`

had to use sudo (might be clue)

`dietpi@DietPi:~$ sudo aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: LouderRaspberry [Louder-Raspberry], device 0: bcm2835-i2s-tas5805m-amplifier tas5805m-amplifier-0 [bcm2835-i2s-tas5805m-amplifier tas5805m-amplifier-0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
`

Power supply is plugged into another computer that supports usb3, but I dont believe PD.  This is because i am getting the UART for debug console.

**Comment by anabolyc** [comment]
If you only see the sound card with `sudo` you should run `cmus` with sudo also. Although that's strange, maybe you're not in the `audio` group (easy to fix)

With power source it is a tricky case, I will document it a little better next week. But long story short, please use another Micro-USB from the same PC to power Pi directly - that's only while developing or debugging. This will solve weird reboots. As soon as you're done with setup and development, you'll need to use PD-enabled power adapter delivering at least 9V on the USB power line

**Comment by luw** [comment]
Again you are correct; all configuration issues.  Playback works perfectly with mpg123.  Thank you for you help sir.

**Comment by anabolyc** [comment]
You're very welcome
