### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by jshep321** [sonocotta/tas5805m-for-raspbian-paspberry-pi-zero#2]
Hi,
Trying to compile and getting the following error.  It is a rpi zero W (not a 2), running the latest bookworm, fully updated.

Tried reinstalling headers and no joy.

Any ideas? 

<img width="1566" alt="image" src="https://github.com/sonocotta/tas5805m-for-raspbian-paspberry-pi-zero/assets/12618683/5cb1e980-42b6-4a18-8cbf-be7d47218042">

**Comment by anabolyc** [comment]
Hey @jshep321 please share your kernel version. I think I had this issue while trying to complete against the latest release. I'll double-check now.

`uname -a`

upd. nevermind, I can see it is `6.6.31` in the attached olg

**Comment by jshep321** [comment]
Yep, you got it.  

More details:  Linux louder 6.6.31+rpt-rpi-v6 #1 Raspbian 1:6.6.31-1+rpt1 (2024-05-29) armv6l GNU/Linux

**Comment by anabolyc** [comment]
@jshep321 I have 6.6.20 with the same result. Can you please try [this branch](https://github.com/sonocotta/tas5805m-for-raspbian-paspberry-pi-zero/tree/features/fix-6.6-kernel-build). Tiny fix, it compiles now. If you can try running it on the device. I can test myself tomorrow.

**Comment by jshep321** [comment]
Worked, thanks!  Another problem that is probably unrelated regarding i2c conflict.  Will write new issue for that.
